### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "permission denied"

### ISSUE THREAD

**Issue by gmcbrien** [fsanys/sonarqube-developer#1]
Hi, I was receiving the following error when running the built image:

```
standard_init_linux.go:211: exec user process caused "permission denied"
```

It was fixed by adding this to the Dockerfile:

```
RUN chmod 755 $SONARQUBE_HOME/bin/run.sh
USER sonarqube
ENTRYPOINT ["/bin/bash","-c","/opt/sonarqube/bin/run.sh"]
```

Not sure if this was unique to my environment,  but maybe it helps someone else.

**Comment by c1rc0le** [comment]
Thanks, let me check if I can reproduce the issue

**Comment by c1rc0le** [comment]
It worked locally for me as the file was with +X permission. I have updated the DockerFile, thanks

**Comment by franciscosuca** [comment]
> Hi, I was receiving the following error when running the built image:
> 
> ```
> standard_init_linux.go:211: exec user process caused "permission denied"
> ```
> 
> It was fixed by adding this to the Dockerfile:
> 
> ```
> RUN chmod 755 $SONARQUBE_HOME/bin/run.sh
> USER sonarqube
> ENTRYPOINT ["/bin/bash","-c","/opt/sonarqube/bin/run.sh"]
> ```
> 
> Not sure if this was unique to my environment, but maybe it helps someone else.

Thanks for your solution, but in my case I only needed the last line as follows:

`ENTRYPOINT ["/bin/ash","./file_name.sh"]`

Without the "-c" and using "ash" instead of "bash" since I am using alpine.

**Comment by c1rc0le** [comment]
Thanks for the tips @franciscosuca !
